parameters:
    ongr_admin.connection.mapping:
        setting:
            mapping:
                properties:
                    name:
                        type: string
                        index: not_analyzed
                    description:
                        type: string
                        index: analyzed
                    domain:
                        type: string
                        index: not_analyzed
                    type:
                        type: string
                        index: not_analyzed
                    data:
                        enabled: false
                        type: object

    ongr_admin.settings_model_connection.settings:
        index:
            number_of_replicas: 1
            number_of_shards: 1
            refresh_interval: -1

services:
    ongr_admin.elastic_search_driver:
        class: Fox\DDALBundle\ElasticSearch\ElasticSearchDriver
        arguments:
            - { host: %database.elastic_search.host%, port: %database.elastic_search.port%, throwCustomExceptions: 1}
            -
              index: %ongr_admin.connection.index_name%
              host: %ongr_admin.connection.host%
              port: %ongr_admin.connection.port%
              map: %ongr_admin.connection.mapping%
              settings: %ongr_admin.settings_model_connection.settings%
              dynamicSettings: %database.elastic_search.dynamic_settings%
              scroll_settings: %database.elastic_search.scroll_settings%
        tags:
            - { name: ongr_ddal.driver, driver: admin }
        calls:
            - [setDisableFlushCall, [1]]
            - [setRefreshOnFlush, [1]]
