ongr_routing_authentication:
    resource: "@ONGRAdminBundle/Resources/config/routing/auth.yml"
    prefix:   /admin

ongr_admin_routing_settings:
    resource: "@ONGRAdminBundle/Resources/config/routing/admin_settings.yml"
    prefix:   /admin

ongr_routing_settings:
    resource: "@ONGRAdminBundle/Resources/config/routing/settings.yml"
    prefix:   /admin