ongr_routing_authentication:
    resource: "@ONGRSettingsBundle/Resources/config/routing/auth.yml"

ongr_settings_routing_settings:
    resource: "@ONGRSettingsBundle/Resources/config/routing/personal_settings.yml"

ongr_routing_settings:
    resource: "@ONGRSettingsBundle/Resources/config/routing/settings.yml"