fox_admin_homepage:
    pattern:  /
    methods: [GET]
    defaults:
        _controller: FoxAdminBundle:SettingsList:list
        domain: 'default'

fox_admin_settings_list:
    pattern:  /list/{domain}
    methods: [GET]
    defaults:
        _controller: FoxAdminBundle:SettingsList:list
        domain: 'default'

fox_admin_setting_set:
    pattern:  /setting/set/{name}/{domain}
    methods: [POST]
    defaults:
        _controller: FoxAdminBundle:SettingsManager:setSetting
        domain: 'default'

fox_admin_setting_edit:
    pattern:  /setting/{name}/edit/{domain}
    methods: [GET, POST]
    defaults:
        _controller: FoxAdminBundle:SettingsManager:edit
        domain: 'default'
    options:
        expose: true

fox_admin_setting_ng_edit:
    pattern:  /setting/ng/{name}/edit/{domain}
    methods: [POST]
    defaults:
        _controller: FoxAdminBundle:SettingsManager:ngEdit
        domain: 'default'
    options:
        expose: true

fox_admin_setting_remove:
    pattern:  /setting/{name}/remove/{domain}
    methods: [DELETE]
    defaults:
        _controller: FoxAdminBundle:SettingsManager:remove
        domain: 'default'
    options:
        expose: true

fox_admin_setting_copy:
    pattern:  /setting/{name}/copy/{from}/{to}
    methods: [GET]
    defaults:
        _controller: FoxAdminBundle:SettingsManager:copy
        from: 'default'
    options:
        expose: true
