ongr_routing_authentication:
    resource: "@ONGRSettingsBundle/Resources/config/routing/auth.yml"
    prefix:   /admin

ongr_settings_routing_settings:
    resource: "@ONGRSettingsBundle/Resources/config/routing/general_settings.yml"
    prefix:   /admin

ongr_routing_settings:
    resource: "@ONGRSettingsBundle/Resources/config/routing/settings.yml"
    prefix:   /admin