ongr_routing_authentication:
    resource: "@ONGRAdminBundle/Resources/config/routing/sessionless_authentication.yml"

ongr_admin_routing_settings:
    resource: "@ONGRAdminBundle/Resources/config/routing/admin_settings.yml"

ongr_routing_settings:
    resource: "@ONGRAdminBundle/Resources/config/routing/settings.yml"
