parameters:
    # Settings structure service.
    ongr_admin.settings.settings_structure.class: ONGR\AdminBundle\Settings\Admin\SettingsStructure
    ongr_admin.settings.settings: []
    ongr_admin.settings.categories: []

    # Cookie service.
    ongr_admin.settings.settings_cookie_service.class: ONGR\AdminBundle\Settings\SettingsCookieService
    ongr_admin.settings.settings_cookie.name: ongr_admin_user_settings
    ongr_admin.settings.settings_cookie.defaults:
        expires_interval: P1Y # 1 year.

    # Cookie listener.
    ongr_admin.settings.settings_cookie_listener.class: ONGR\AdminBundle\EventListener\SettingsCookieListener

    # Admin Settings manager service class.
    ongr_admin.settings.admin_settings_manager.class: ONGR\AdminBundle\Settings\Admin\AdminSettingsManager

    # Admin profiles provider.
    ongr_admin.admin_profiles_provider.class: ONGR\AdminBundle\Settings\Admin\AdminProfilesProvider

services:
    ongr_admin.settings.settings_structure:
        class: %ongr_admin.settings.settings_structure.class%
        arguments:
            - %ongr_admin.settings.settings%
            - %ongr_admin.settings.categories%

    ongr_admin.settings.settings_cookie_service:
        class: %ongr_admin.settings.settings_cookie_service.class%
        arguments:
            - %ongr_admin.settings.settings_cookie.name%

    ongr_admin.settings.settings_cookie_listener:
        class: %ongr_admin.settings.settings_cookie_listener.class%
        calls:
            - [ setAdminSettingsManager, [ @ongr_admin.settings.admin_settings_manager ] ]
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 6 }
        scope: request

    ongr_admin.settings.settings_cookie:
        class: %ongr_cookie.json.class%
        arguments: [ %ongr_admin.settings.settings_cookie.name% ]
        calls:
            - [ setDefaults, [ %ongr_admin.settings.settings_cookie.defaults% ] ]
        tags:
            - { name: ongr_cookie.cookie }

    #Admin settings manager class
    ongr_admin.settings.admin_settings_manager:
        class: %ongr_admin.settings.admin_settings_manager.class%
        arguments:
            - @security.authorization_checker
            - @ongr_admin.settings.settings_structure

    # Admin profiles provider
    ongr_admin.admin_profiles_provider:
        class: %ongr_admin.admin_profiles_provider.class%
        calls:
            - [ setProfileManager, [ @ongr_admin.profiles_manager ] ]
            - [ setSettingsStructure, [ @ongr_admin.settings.settings_structure ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
