parameters:
    ongr_admin.flash_bag.flash_bag.class: ONGR\AdminBundle\FlashBag\DirtyFlashBag
    ongr_admin.flash_bag.cookie.name: ongr_flash_bag
    ongr_admin.flash_bag.cookie.injector.class: ONGR\AdminBundle\EventListener\FlashBagCookieInjectorListener

services:
    ongr_admin.flash_bag.flash_bag:
        class: %ongr_admin.flash_bag.flash_bag.class%

    ongr_admin.flash_bag.cookie:
        class: %ongr_admin.cookie.json.class%
        arguments: [ %ongr_admin.flash_bag.cookie.name% ]
        tags:
            - { name: ongr_admin.cookie }

    ongr_admin.flash_bag.cookie.injector:
        class: %ongr_admin.flash_bag.cookie.injector.class%
        arguments: [ @ongr_admin.flash_bag.flash_bag, @ongr_admin.flash_bag.cookie ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 96 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
