parameters:
    ongr_settings.pair_storage.class: ONGR\SettingsBundle\Service\PairStorage

services:
    ongr_settings.pair_storage:
        class: %ongr_settings.pair_storage.class%
        arguments:
            - @es.manager
