parameters:
    # Settings structure service
    ongr_admin.settings.settings_structure.class: ONGR\AdminBundle\Settings\Common\SettingsStructure
    ongr_admin.settings.settings: []
    ongr_admin.settings.categories: []

    # Settings manager
    ongr_admin.settings_manager.class: ONGR\AdminBundle\Service\SettingsManager

    ongr_admin.settings_container.class: ONGR\AdminBundle\Settings\Common\SettingsContainer
    ongr_admin.setting_aware_service_factory.class: ONGR\AdminBundle\Service\SettingAwareServiceFactory
    ongr_admin.listener.cookie_profile.class: ONGR\AdminBundle\EventListener\ProfileRequestListener
    ongr_admin.profiles_manager.class: ONGR\AdminBundle\Service\ProfilesManager

    ongr_admin.settings_provider.class: ONGR\AdminBundle\Settings\Common\Provider\ManagerAwareSettingProvider
#    ongr_admin.power_user_profiles_provider.class: ONGR\AdminBundle\Settings\PowerUserProfilesProvider

services:
    ongr_admin.settings.settings_structure:
        class: %ongr_admin.settings.settings_structure.class%
        arguments:
            - %ongr_admin.settings.settings%
            - %ongr_admin.settings.categories%

    ongr_admin.settings_manager:
        class: %ongr_admin.settings_manager.class%
        arguments:
            - @translator
            - @event_dispatcher
            - @es.manager

    ongr_admin.settings_container:
        class: %ongr_admin.settings_container.class%
        arguments:
            - @stash
            - %ongr_admin.settings_container.profiles%
        tags:
            - { name: kernel.event_listener, event: ongr_admin.setting_change, method: onSettingChange }

    ongr_admin.setting_aware_service_factory:
        class: %ongr_admin.setting_aware_service_factory.class%
        arguments:
            - @ongr_admin.settings_container
        calls:
            - [setLogger, [@?logger]]
        tags:
            - { name: monolog.logger, channel: admin }

    ongr_admin.listener.cookie_profile:
        class: %ongr_admin.listener.cookie_profile.class%
        calls:
            - [setSettingsContainer, [@ongr_admin.settings_container]]
            - [setAdminSettingsManager, [@ongr_admin.settings.admin_settings_manager]]
            - [setManager, [@es.manager]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    ongr_admin.profiles_manager:
        class: %ongr_admin.profiles_manager.class%
        arguments:
            - @es.manager

#    ongr_admin.power_user_profiles_provider:
#        class: %ongr_admin.power_user_profiles_provider.class%
#        calls:
#            - [setProfileManager, [@ongr_admin.profiles_manager]]
#            - [setSettingsStructure, [@ongr_admin.settings.settings_structure]]
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
