parameters:
    ongr_admin.twig.admin_extension.class: ONGR\AdminBundle\Twig\AdminExtension
    ongr_admin.twig.encryption_extension.class: ONGR\AdminBundle\Twig\EncryptionExtension
    ongr_admin.twig.wrapper_extension.class: ONGR\AdminBundle\Twig\WrapperExtension
    ongr_admin.twig.slugify_extension.class: ONGR\AdminBundle\Twig\SlugifyExtension
    ongr_admin.twig.hidden_extension.class: ONGR\AdminBundle\Twig\HiddenExtension
    ongr_admin.twig.setting_extension.class: ONGR\AdminBundle\Twig\SettingExtension
    ongr_admin.twig.extension.pager.class: ONGR\AdminBundle\Twig\PagerExtension

services:
    ongr_admin.twig.admin_extension:
        class: %ongr_admin.twig.admin_extension.class%
        arguments:
            - @ongr_admin.settings.user_settings_manager
        calls:
            - [setSettingsContainer, [@ongr_admin.settings_container]]
            - [setLogger, [@?logger]]
        tags:
            - { name: twig.extension }
            - { name: monolog.logger, channel: admin }

#    ongr_utils.twig.extension.pager:
#        class: %ongr_utils.twig.extension.pager.class%
#        arguments:
#            - @router
#        tags:
#            - { name: twig.extension, alias: pager }
#
#    ongr_utils.twig.price_extension:
#        class: %ongr_utils.twig.price_extension.class%
#        tags:
#          - { name: twig.extension }
#        arguments:
#          - %ongr_utils.twig.price_extension.currency.sign%
#          - %ongr_utils.twig.price_extension.currency.dec_point_separator%
#          - %ongr_utils.twig.price_extension.currency.thousands_separator%
#          - %ongr_utils.twig.price_extension.currency.name%
#          - %ongr_utils.twig.price_extension.display_map%
#          - %ongr_utils.twig.price_extension.to_print_list%
#
#    ongr_utils.twig.image_path_extension:
#        class: %ongr_utils.twig.image_path_extension.class%
#        tags:
#          - { name: twig.extension }
#        arguments:
#          - %ongr_utils.twig.image_path_extension.cdn_url%
#          -
#            'presets': %ongr_utils.twig.image_path_extension.image_presets%
#            'mapping': %ongr_utils.twig.image_path_extension.image_fields_mapping%
#          - %ongr_utils.twig.image_path_extension.images_cache_prefix%
#
#    ongr_utils.twig.loader_extension:
#        class: Twig_Extension_StringLoader
#        tags:
#          - { name: 'twig.extension' }
#
#    ongr_utils.twig.checkout_extension:
#        class: %ongr_utils.twig.checkout_extension.class%
#        tags:
#          - { name: twig.extension }
#        arguments:
#          - @service_container
#          - %ongr_utils.twig.checkout_extension.checkout_path%
#          - %ongr_utils.twig.checkout_extension.ssl%
#
#    ongr_utils.twig.encryption_extension:
#        class: %ongr_utils.twig.encryption_extension.class%
#        tags:
#          - { name: twig.extension }
#
#    ongr_utils.twig.wrapper_extension:
#        class: %ongr_utils.twig.wrapper_extension.class%
#        tags:
#          - { name: twig.extension }
#

#    ongr_utils.twig.slugify_extension:
#        class: %ongr_utils.twig.slugify_extension.class%
#        tags:
#          - { name: twig.extension }
#
    ongr_utils.twig.setting_extension:
        class: %ongr_admin.twig.setting_extension.class%
        arguments:
          - @ongr_admin.settings.user_settings_manager
        tags:
          - { name: twig.extension }

#    ongr_utils.twig.hidden_extension:
#            class: %ongr_utils.twig.hidden_extension.class%
#            arguments:
#              - @service_container
#            tags:
#              - { name: twig.extension }