parameters:
    #Application settings widget extension
    ongr_admin.twig.admin_extension.class: ONGR\AdminBundle\Twig\SettingWidgetExtension

    #Admin settings widget extension
    ongr_admin.twig.setting_extension.class: ONGR\AdminBundle\Twig\AdminSettingWidgetExtension

    # Encryption extension
    ongr_admin.twig.encryption_extension.class: ONGR\AdminBundle\Twig\EncryptionExtension

    # Hidden extension
    ongr_admin.twig.hidden_extension.class: ONGR\AdminBundle\Twig\HiddenExtension

    # Image path extension
    ongr_admin.twig.image_path_extension.class: ONGR\AdminBundle\Twig\ImagePathExtension
    ongr_admin.twig.image_path_extension.cdn_url: //cdn.fox-project.com
    ongr_admin.twig.image_path_extension.image_presets: ~
    ongr_admin.twig.image_path_extension.image_fields_mapping: ~
    ongr_admin.twig.image_path_extension.images_cache_prefix: /cdn

    # Wrapper extension
    ongr_admin.twig.wrapper_extension.class: ONGR\AdminBundle\Twig\WrapperExtension

services:
    ongr_admin.twig.admin_extension:
        class: %ongr_admin.twig.admin_extension.class%
        arguments:
            - @ongr_admin.settings.admin_settings_manager
        calls:
            - [setSettingsContainer, [@ongr_admin.settings_container]]
            - [setLogger, [@?logger]]
        tags:
            - { name: twig.extension }
            - { name: monolog.logger, channel: admin }

    ongr_utils.twig.setting_extension:
        class: %ongr_admin.twig.setting_extension.class%
        arguments:
          - @ongr_admin.settings.admin_settings_manager
        tags:
          - { name: twig.extension }

    ongr_admin.twig.encryption_extension:
        class: %ongr_admin.twig.encryption_extension.class%
        tags:
          - { name: twig.extension }

    ongr_admin.twig.hidden_extension:
            class: %ongr_admin.twig.hidden_extension.class%
            arguments:
              - @service_container
            tags:
              - { name: 'twig.extension' }

    ongr_admin.twig.image_path_extension:
        class: %ongr_admin.twig.image_path_extension.class%
        tags:
          - { name: 'twig.extension' }
        arguments:
          - %ongr_admin.twig.image_path_extension.cdn_url%
          -
            'presets': %ongr_admin.twig.image_path_extension.image_presets%
            'mapping': %ongr_admin.twig.image_path_extension.image_fields_mapping%
          - %ongr_admin.twig.image_path_extension.images_cache_prefix%

    ongr_admin.twig.loader_extension:
        class: Twig_Extension_StringLoader
        tags:
          - { name: 'twig.extension' }

    ongr_admin.twig.wrapper_extension:
        class: %ongr_admin.twig.wrapper_extension.class%
        tags:
          - { name: 'twig.extension' }

