language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  - SYMFONY="2.6.*"
services:
  - elasticsearch
install:
  - "echo 'script.disable_dynamic: false' | sudo tee -a /etc/elasticsearch/elasticsearch.yml"
  - sudo service elasticsearch restart
before_script:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer update --prefer-dist
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -p --standard=$TRAVIS_BUILD_DIR/vendor/ongr/ongr-strict-standard/Ongr --ignore=vendor/,Tests/app/,Resources/public/ ./
