ongr_admin_sessionless_login:
    path: /login
    defaults:
        _controller: ONGRAdminBundle:User:login

ongr_admin_sessionless_logout:
    path: /logout
    defaults:
        _controller: ONGRAdminBundle:User:logout
