#Admin settings
ongr_admin_settings_settings:
    path: /settings
    defaults:
        _controller: ONGRAdminBundle:AdminSettings:settings

ongr_admin_settings_change:
    path: /setting/change/{hash}
    defaults:
        _controller: ONGRAdminBundle:AdminSettings:changeSetting
        methods: [GET]

#Common settings
ongr_admin_homepage:
    pattern:  /
    methods: [GET]
    defaults:
        _controller: ONGRAdminBundle:SettingsList:list
        profile: 'default'

ongr_admin_settings_list:
    pattern:  /list/{profile}
    methods: [GET]
    defaults:
        _controller: ONGRAdminBundle:SettingsList:list
        profile: 'default'

ongr_admin_setting_set:
    pattern:  /setting/set/{name}/{profile}
    methods: [POST]
    defaults:
        _controller: ONGRAdminBundle:SettingsManager:setSetting
        profile: 'default'

ongr_admin_setting_edit:
    pattern:  /setting/{name}/edit/{profile}
    methods: [GET, POST]
    defaults:
        _controller: ONGRAdminBundle:SettingsManager:edit
        profile: 'default'
    options:
        expose: true

ongr_admin_setting_ng_edit:
    pattern:  /setting/ng/{name}/edit/{profile}
    methods: [POST]
    defaults:
        _controller: ONGRAdminBundle:SettingsManager:ngEdit
        profile: 'default'
    options:
        expose: true

ongr_admin_setting_remove:
    pattern:  /setting/{name}/remove/{profile}
    methods: [DELETE]
    defaults:
        _controller: ONGRAdminBundle:SettingsManager:remove
        profile: 'default'
    options:
        expose: true

ongr_admin_setting_copy:
    pattern:  /setting/{name}/copy/{from}/{to}
    methods: [GET]
    defaults:
        _controller: ONGRAdminBundle:SettingsManager:copy
        from: 'default'
    options:
        expose: true