ongr_admin_settings_settings:
    path: /settings
    defaults:
        _controller: ONGRAdminBundle:Settings:settings

ongr_admin_settings_change:
    path: /setting/change/{hash}
    defaults:
        _controller: ONGRAdminBundle:Settings:changeSetting
        methods: [GET]
